content:
  - name: leituras
    label: Leituras
    type: collection
    path: content/leituras
    fields:
      - { name: artists, label: Artistas, type: string, required: true }
      - { name: title, label: Título, type: string, required: true }
      