media:
  - name: covers
    label: Capas de Leituras
    input: public/images/covers
    output: /public/images/covers
    extensions: [ webp ]
  - name: covers-notes
    label: Capas de Notas
    input: public/images/notes
    output: /public/images/notes
    extensions: [ webp ]
content:
  - name: leituras
    label: Leituras
    type: collection
    path: content/leituras
    filename: '{primary}.md'
    fields:
      - { name: title, label: Título, type: string, required: true }
      - { name: artists, label: Artistas, type: string, list: true, required: true }
      - { name: collection, label: Coleção, type: string, required: false }
      - { name: collectionVolume, label: Volume da Coleção, type: number, required: false }
      - { name: cover, label: Capa (URL), type: string, required: true }
      - { name: date, label: Data de leitura, type: date, required: true }
      - { name: dateNote, label: Data da nota, type: date, required: false }
      - { name: labels, label: Labels, type: string, list: true, required: true }
      - { name: pages, label: Qtd. de Páginas, type: number, required: true }
      - name: publisher
        label: Editora
        type: select
        options:
          creatable: true
          multiple: true
          values: [ ComixZone, Conrad, DarkSide, JBC, Mino, Mistifório, Monstra, MPEG, Panini, Pé-de-Cabra, Pipoca & Nanquim, Suma, Veneta ]
      - { name: publishYear, label: Ano de Publicação, type: string, required: true }
      - { name: rating, label: Avaliação, type: string, required: true }
  - name: notas
    label: Notas
    type: collection
    path: content/notas
    filename: '{primary}.md'
    fields: 
      - { name: title, label: Título, type: string, required: true }      
      - { name: collection, label: Coleções, type: string, list: true, required: false }
      - { name: cover, label: Capa (URL), type: string, required: true }
      - { name: dateNote, label: Data da nota, type: date, required: true }
      - { name: tags, label: Tags da Nota, type: string,, list: true, required: false }
      - name: body
        label: Body
        type: rich-text
